#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width     2
bspc config window_gap       6
bspc config top_padding     25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a ranger floating=on

$HOME/.scripts/polybar_launch
