#! /bin/sh

sxhkd &

bspc monitor -d browser code files media download misc

bspc config border_width     2
bspc config window_gap       6
bspc config top_padding     25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config external_rules_command "$(which external_rules)"

bspc rule -a urxvt state=floating
bspc rule -a ranger:* state=floating
bspc rula -a mpv:* state=floating

bspc rule -a Godot:* state=floating

$HOME/.scripts/polybar_launch
