#! /bin/sh

sxhkd &

bspc monitor -d browser code files media download misc

bspc config border_width     2
bspc config window_gap       6
bspc config top_padding     25

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a ranger floating=on
bspc rule -a google-chrome desktop=^1 follow=on state=fullscreen
bspc rule -a Godot_Engine state=floating

$HOME/.scripts/polybar_launch
