#!/bin/sh

source bar-colors.sh

get_title() {
    xtitle
}

get_time() {
    echo -n "$(date "+%H:%M")"
}

get_date() {
    echo -n "$(date "+%a %-e %b")"
}

Battery() {
    BATTERY_PERCENTAGE=$(acpi --battery | cut -d" " -f 4 | sed 's/[^0-9]*//g')
    BATTERY_STATUS=$( acpi --battery | tail -n 1 | cut -d" " -f 3 | sed 's/,$//' )
    BATTERY_ICON=""
    BAT_COL="$FG"

    case $BATTERY_STATUS in
           'Charging') BATTERY_ICON="" ;;
           'Full') BATTERY_ICON="" ;;
           'Discharging')
               if [ $BATTERY_PERCENTAGE -ge 90 ]; then BATTERY_ICON=""; fi
               if [ $BATTERY_PERCENTAGE -le 89 ]; then BATTERY_ICON=""; fi
               if [ $BATTERY_PERCENTAGE -le 60 ]; then BATTERY_ICON=""; fi
               if [ $BATTERY_PERCENTAGE -le 30 ]; then BATTERY_ICON=""; fi
               if [ $BATTERY_PERCENTAGE -le 10 ]; then BATTERY_ICON=""; BAT_COL="$RED"; fi
               ;;
    esac

    # echo "%{F$BAT_COL}%{T5}$BATTERY_ICON%{T-}%{F-} $BATTERY_PERCENTAGE%"
    echo "%{F$BAT_COL}%{T5}$BATTERY_ICON%{T-}%{F-}"
}





while true; do
    echo -e "%{c}$(get_title) \
             %{r}$(Battery) | $(get_time) $(get_date)" 
    sleep 1;
done
